#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other '/bin/sh' around, it may work, but
#       please be careful to ''exec'' that shell to final time around, because
#       ShellCheck may complain.
#
#   (2) The switching of this script ON or OFF will be done by setting the
#       GRADLE_SKIP_VALIDATION environment variable to "true" or "false" respectively.
#
##############################################################################

set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APP_HOME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

APP_NAME="Gradle"
APP_JAR="${APP_HOME}/gradle/wrapper/gradle-wrapper.jar"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    if [ "$VERBOSE" = yes ]; then
        printf '%s\n' "$*"
    fi
}

die() {
    printf '%s\n' "$*" >&2
    exit 1
}

case $( uname ) in                #(
  CYGWIN* )         CYGWIN=yes;; #(
  Darwin* )         DARWIN=yes;; #(
  MSYS* | MINGW* )  MSYS=yes;;    #(
  NOTO* )           NOTO="yes";;  #(
  * )               ;;
esac

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$CYGWIN" = "yes" ] || [ "$MSYS" = "yes" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    APP_JAR=$( cygpath --path --mixed "$APP_JAR" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false;;                            # don't mess with options #(
              /?*)  t=${arg#/};t=/${t%%/*};            # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false;;                             #(
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        args="$args $arg"
    done
fi

if [ -z "$GRADLE_HOME" ]; then
    GRADLE_HOME="$( find . -type f -name "gradle" | head -1 | xargs dirname )"
fi

exec "$JAVACMD" "$@"
